
# This file was *autogenerated* from the file hw1.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_200 = Integer(200); _sage_const_100 = Integer(100); _sage_const_91 = Integer(91); _sage_const_87 = Integer(87); _sage_const_79 = Integer(79); _sage_const_83 = Integer(83); _sage_const_10 = Integer(10); _sage_const_76 = Integer(76); _sage_const_300 = Integer(300); _sage_const_0 = Integer(0); _sage_const_50 = Integer(50)## This file (hw1.sage) was *autogenerated* from the file hw1.tex.
import sagetex
_st_ = sagetex.SageTeXProcessor('hw1')
_st_.blockbegin()
try:
 from random import randint
 var('A,B,C,D')
 A = randint(_sage_const_10 ,_sage_const_100 )
 B = randint(_sage_const_10 ,_sage_const_200 )
 C = randint(_sage_const_10 ,_sage_const_300 )
 D = randint(_sage_const_10 ,_sage_const_50 )
except:
 _st_.goboom(_sage_const_76 )
_st_.blockend()
try:
 _st_.inline(_sage_const_0 , A)
except:
 _st_.goboom(_sage_const_79 )
try:
 _st_.inline(_sage_const_1 , B)
except:
 _st_.goboom(_sage_const_83 )
try:
 _st_.inline(_sage_const_2 , C)
except:
 _st_.goboom(_sage_const_87 )
try:
 _st_.inline(_sage_const_3 , D)
except:
 _st_.goboom(_sage_const_91 )
_st_.endofdoc()

