## -*- encoding: utf-8 -*-

# This file was *autogenerated* from the file hw1.sagetex.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_7 = Integer(7); _sage_const_6 = Integer(6); _sage_const_5 = Integer(5); _sage_const_4 = Integer(4); _sage_const_9 = Integer(9); _sage_const_8 = Integer(8); _sage_const_32 = Integer(32); _sage_const_11 = Integer(11); _sage_const_10 = Integer(10); _sage_const_18 = Integer(18); _sage_const_25 = Integer(25)## This file (hw1.sagetex.sage) was *autogenerated* from hw1.tex with sagetex.sty version 2015/08/26 v3.0-92d9f7a.
import sagetex
_st_ = sagetex.SageTeXProcessor('hw1', version='2015/08/26 v3.0-92d9f7a', version_check=True)
_st_.current_tex_line = _sage_const_8 
_st_.blockbegin()
try:
     var('A, B, y')
     A = matrix([[randint(-_sage_const_11 ,_sage_const_11 ), randint(-_sage_const_11 ,_sage_const_11 )], [randint(-_sage_const_11 ,_sage_const_11 ), randint(-_sage_const_11 ,_sage_const_11 )]])
     B = vector([randint(-_sage_const_11 ,_sage_const_11 ),randint(-_sage_const_11 ,_sage_const_11 )])
 
 
     var('C, D')
     C = matrix([[randint(-_sage_const_11 ,_sage_const_11 ), randint(-_sage_const_11 ,_sage_const_11 )], [randint(-_sage_const_11 ,_sage_const_11 ), randint(-_sage_const_11 ,_sage_const_11 )]])
     D = vector([randint(-_sage_const_11 ,_sage_const_11 ),randint(-_sage_const_11 ,_sage_const_11 )])
 
except:
 _st_.goboom(_sage_const_18 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_25 
 _st_.inline(_sage_const_0 , latex(A[_sage_const_0 ][_sage_const_0 ]))
except:
 _st_.goboom(_sage_const_25 )
try:
 _st_.current_tex_line = _sage_const_25 
 _st_.inline(_sage_const_1 , latex(A[_sage_const_0 ][_sage_const_1 ]))
except:
 _st_.goboom(_sage_const_25 )
try:
 _st_.current_tex_line = _sage_const_25 
 _st_.inline(_sage_const_2 , latex(B[_sage_const_0 ]))
except:
 _st_.goboom(_sage_const_25 )
try:
 _st_.current_tex_line = _sage_const_25 
 _st_.inline(_sage_const_3 , latex(A[_sage_const_1 ][_sage_const_0 ]))
except:
 _st_.goboom(_sage_const_25 )
try:
 _st_.current_tex_line = _sage_const_25 
 _st_.inline(_sage_const_4 , latex(A[_sage_const_1 ][_sage_const_1 ]))
except:
 _st_.goboom(_sage_const_25 )
try:
 _st_.current_tex_line = _sage_const_25 
 _st_.inline(_sage_const_5 , latex(B[_sage_const_1 ]))
except:
 _st_.goboom(_sage_const_25 )
try:
 _st_.current_tex_line = _sage_const_25 
 _st_.inline(_sage_const_0 , latex(A[_sage_const_0 ][_sage_const_0 ]))
except:
 _st_.goboom(_sage_const_25 )
try:
 _st_.current_tex_line = _sage_const_25 
 _st_.inline(_sage_const_1 , latex(A[_sage_const_0 ][_sage_const_1 ]))
except:
 _st_.goboom(_sage_const_25 )
try:
 _st_.current_tex_line = _sage_const_25 
 _st_.inline(_sage_const_2 , latex(B[_sage_const_0 ]))
except:
 _st_.goboom(_sage_const_25 )
try:
 _st_.current_tex_line = _sage_const_25 
 _st_.inline(_sage_const_3 , latex(A[_sage_const_1 ][_sage_const_0 ]))
except:
 _st_.goboom(_sage_const_25 )
try:
 _st_.current_tex_line = _sage_const_25 
 _st_.inline(_sage_const_4 , latex(A[_sage_const_1 ][_sage_const_1 ]))
except:
 _st_.goboom(_sage_const_25 )
try:
 _st_.current_tex_line = _sage_const_25 
 _st_.inline(_sage_const_5 , latex(B[_sage_const_1 ]))
except:
 _st_.goboom(_sage_const_25 )
try:
 _st_.current_tex_line = _sage_const_32 
 _st_.inline(_sage_const_6 , latex(C[_sage_const_0 ][_sage_const_0 ]))
except:
 _st_.goboom(_sage_const_32 )
try:
 _st_.current_tex_line = _sage_const_32 
 _st_.inline(_sage_const_7 , latex(C[_sage_const_0 ][_sage_const_1 ]))
except:
 _st_.goboom(_sage_const_32 )
try:
 _st_.current_tex_line = _sage_const_32 
 _st_.inline(_sage_const_8 , latex(D[_sage_const_0 ]))
except:
 _st_.goboom(_sage_const_32 )
try:
 _st_.current_tex_line = _sage_const_32 
 _st_.inline(_sage_const_9 , latex(C[_sage_const_1 ][_sage_const_0 ]))
except:
 _st_.goboom(_sage_const_32 )
try:
 _st_.current_tex_line = _sage_const_32 
 _st_.inline(_sage_const_10 , latex(C[_sage_const_1 ][_sage_const_1 ]))
except:
 _st_.goboom(_sage_const_32 )
try:
 _st_.current_tex_line = _sage_const_32 
 _st_.inline(_sage_const_11 , latex(D[_sage_const_1 ]))
except:
 _st_.goboom(_sage_const_32 )
try:
 _st_.current_tex_line = _sage_const_32 
 _st_.inline(_sage_const_6 , latex(C[_sage_const_0 ][_sage_const_0 ]))
except:
 _st_.goboom(_sage_const_32 )
try:
 _st_.current_tex_line = _sage_const_32 
 _st_.inline(_sage_const_7 , latex(C[_sage_const_0 ][_sage_const_1 ]))
except:
 _st_.goboom(_sage_const_32 )
try:
 _st_.current_tex_line = _sage_const_32 
 _st_.inline(_sage_const_8 , latex(D[_sage_const_0 ]))
except:
 _st_.goboom(_sage_const_32 )
try:
 _st_.current_tex_line = _sage_const_32 
 _st_.inline(_sage_const_9 , latex(C[_sage_const_1 ][_sage_const_0 ]))
except:
 _st_.goboom(_sage_const_32 )
try:
 _st_.current_tex_line = _sage_const_32 
 _st_.inline(_sage_const_10 , latex(C[_sage_const_1 ][_sage_const_1 ]))
except:
 _st_.goboom(_sage_const_32 )
try:
 _st_.current_tex_line = _sage_const_32 
 _st_.inline(_sage_const_11 , latex(D[_sage_const_1 ]))
except:
 _st_.goboom(_sage_const_32 )
_st_.endofdoc()

