
# This file was *autogenerated* from the file hw4.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_200 = Integer(200); _sage_const_7 = Integer(7); _sage_const_6 = Integer(6); _sage_const_5 = Integer(5); _sage_const_4 = Integer(4); _sage_const_9 = Integer(9); _sage_const_8 = Integer(8); _sage_const_0 = Integer(0); _sage_const_1p03 = RealNumber('1.03'); _sage_const_67 = Integer(67); _sage_const_86 = Integer(86); _sage_const_81 = Integer(81); _sage_const_83 = Integer(83); _sage_const_p03 = RealNumber('.03'); _sage_const_151 = Integer(151); _sage_const_12 = Integer(12); _sage_const_11 = Integer(11); _sage_const_10 = Integer(10); _sage_const_50 = Integer(50); _sage_const_100 = Integer(100); _sage_const_101 = Integer(101); _sage_const_103 = Integer(103); _sage_const_106 = Integer(106); _sage_const_144 = Integer(144); _sage_const_147 = Integer(147); _sage_const_142 = Integer(142); _sage_const_300 = Integer(300)## This file (hw4.sage) was *autogenerated* from the file hw4.tex.
import sagetex
_st_ = sagetex.SageTeXProcessor('hw4')
_st_.blockbegin()
try:
 from random import randint
 import random
 from datetime import datetime
 random.seed(datetime.now())
 import numpy as np
 var('A,B,C,D')
except:
 _st_.goboom(_sage_const_67 )
_st_.blockend()
_st_.blockbegin()
try:
 A = randint(_sage_const_10 ,_sage_const_100 )
 B = randint(_sage_const_10 ,_sage_const_200 )
 C = randint(_sage_const_10 ,_sage_const_300 )
 D = B
 P = line([[A,B],[C,D]])
 Q = point([A,B])
 S = point([C,D])
except:
 _st_.goboom(_sage_const_81 )
_st_.blockend()
try:
 _st_.plot(_sage_const_0 , format='notprovided', _p_=P+Q+S)
except:
 _st_.goboom(_sage_const_83 )
try:
 _st_.inline(_sage_const_0 , A)
except:
 _st_.goboom(_sage_const_86 )
try:
 _st_.inline(_sage_const_1 , B)
except:
 _st_.goboom(_sage_const_86 )
try:
 _st_.inline(_sage_const_2 , C)
except:
 _st_.goboom(_sage_const_86 )
try:
 _st_.inline(_sage_const_3 , D)
except:
 _st_.goboom(_sage_const_86 )
_st_.blockbegin()
try:
 A = randint(_sage_const_10 ,_sage_const_100 )
 B = randint(_sage_const_10 ,_sage_const_200 )
 C = A
 D = randint(_sage_const_10 ,_sage_const_50 )
 P = line([[A,B],[C,D]])
 Q = point([A,B])
 S = point([C,D])
except:
 _st_.goboom(_sage_const_101 )
_st_.blockend()
try:
 _st_.plot(_sage_const_1 , format='notprovided', _p_=P+Q+S)
except:
 _st_.goboom(_sage_const_103 )
try:
 _st_.inline(_sage_const_4 , A)
except:
 _st_.goboom(_sage_const_106 )
try:
 _st_.inline(_sage_const_5 , B)
except:
 _st_.goboom(_sage_const_106 )
try:
 _st_.inline(_sage_const_6 , C)
except:
 _st_.goboom(_sage_const_106 )
try:
 _st_.inline(_sage_const_7 , D)
except:
 _st_.goboom(_sage_const_106 )
_st_.blockbegin()
try:
 var('m')
 y = function('y')
 m = randint(-_sage_const_5 ,_sage_const_5 )
 A = randint(_sage_const_10 ,_sage_const_100 )
 B = randint(_sage_const_10 ,_sage_const_200 )
 C = randint(_sage_const_10 ,_sage_const_300 )
 D = B
 E = C
 F = randint(_sage_const_10 , _sage_const_300 )
 
 P = line([[A,B],[C,D]])
 Q = line([[C,D],[E,F]])
 R = point([A,B])
 S = point([C,D])
 T = point([E,F])
 
 
 LA = text('A', (A,B+_sage_const_p03 *max(D,B,max(y(A),y(C)))))
 LB = text('B', (C+_sage_const_p03 *C, D))
 LC = text('C', (_sage_const_1p03 *E, F))
 
except:
 _st_.goboom(_sage_const_142 )
_st_.blockend()
try:
 _st_.plot(_sage_const_2 , format='notprovided', _p_=P+Q+R+S+T+LA+LB+LC)
except:
 _st_.goboom(_sage_const_144 )
try:
 _st_.inline(_sage_const_8 , A)
except:
 _st_.goboom(_sage_const_147 )
try:
 _st_.inline(_sage_const_9 , B)
except:
 _st_.goboom(_sage_const_147 )
try:
 _st_.inline(_sage_const_10 , C)
except:
 _st_.goboom(_sage_const_147 )
try:
 _st_.inline(_sage_const_11 , D)
except:
 _st_.goboom(_sage_const_147 )
try:
 _st_.inline(_sage_const_12 , y(x))
except:
 _st_.goboom(_sage_const_151 )
_st_.endofdoc()

